/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/accounts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description WARNING: This endpoint is only available to partner organisations. */
        post: operations["Create an account"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/{account_number}/tariff-renewal/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description This end-point allows a new agreement to be created for an existing account. It is restricted to business accounts. WARNING: This endpoint is only available to partner organisations. */
        post: operations["Renew a business tariff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/electricity-meter-points/{mpan}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve the details of a meter-point. This endpoint can be used to get the GSP of a given meter-point. */
        get: operations["Get Electricity Meter Point"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/electricity-meter-points/{mpan}/meters/{serial_number}/consumption/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return a list of consumption values (in kWh) for half-hour periods for a given meter-point and meter. WARNING: Half-hourly consumption data is only available for smart meters. Requests for consumption data for non-smart meters will return an empty response payload. */
        get: operations["List consumption for an electricity meter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/gas-meter-points/{mprn}/meters/{serial_number}/consumption/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return a list of consumption values (in kWh for SMETS1 and in m^3 for SMETS2) for half-hour periods for a given gas meter-point and meter. WARNING: Half-hourly consumption data is only available for smart meters. Requests for consumption data for non-smart meters will return an empty response payload. */
        get: operations["List consumption for a gas meter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/industry/grid-supply-points/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return a list of GSP objects, optionally filtered by postcode. If we’re unable to map the passed postcode to a GSP, an empty list will be returned */
        get: operations["List Industry Grid Supply Points"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ivr-support/minimal-enqueue-for-incidents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Enqueue a call from Twilio with the fewest steps.
         *
         *     Designed to point phone numbers at when Studio is unavailable.
         *     May also be useful to mitigate other types of incident.
         *     Performs the minimal amount of work to enqueue a call, storing a record of it.
         *     As such, non-essential work is omitted. */
        post: operations["Minimal Twilio Enqueue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return a list of energy products. By default, results will be public energy products but if the authenticated organisations will also see products available to their organisation. */
        get: operations["List Products"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{product_code}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve the details of a product (including all its tariffs) for a particular point in time. */
        get: operations["Retrieve a Product"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{product_code}/electricity-tariffs/{tariff_code}/day-unit-rates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Abstract base class for generic types.
         *
         *     On Python 3.12 and newer, generic classes implicitly inherit from
         *     Generic when they declare a parameter list after the class's name::
         *
         *         class Mapping[KT, VT]:
         *             def __getitem__(self, key: KT) -> VT:
         *                 ...
         *             # Etc.
         *
         *     On older versions of Python, however, generic classes have to
         *     explicitly inherit from Generic.
         *
         *     After a class has been declared to be generic, it can then be used as
         *     follows::
         *
         *         def lookup_name[KT, VT](mapping: Mapping[KT, VT], key: KT, default: VT) -> VT:
         *             try:
         *                 return mapping[key]
         *             except KeyError:
         *                 return default */
        get: operations["List Electricity Tariff Day Unit Rates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{product_code}/electricity-tariffs/{tariff_code}/night-unit-rates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Abstract base class for generic types.
         *
         *     On Python 3.12 and newer, generic classes implicitly inherit from
         *     Generic when they declare a parameter list after the class's name::
         *
         *         class Mapping[KT, VT]:
         *             def __getitem__(self, key: KT) -> VT:
         *                 ...
         *             # Etc.
         *
         *     On older versions of Python, however, generic classes have to
         *     explicitly inherit from Generic.
         *
         *     After a class has been declared to be generic, it can then be used as
         *     follows::
         *
         *         def lookup_name[KT, VT](mapping: Mapping[KT, VT], key: KT, default: VT) -> VT:
         *             try:
         *                 return mapping[key]
         *             except KeyError:
         *                 return default */
        get: operations["List Electricity Tariff Night Unit Rates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{product_code}/electricity-tariffs/{tariff_code}/standard-unit-rates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Abstract base class for generic types.
         *
         *     On Python 3.12 and newer, generic classes implicitly inherit from
         *     Generic when they declare a parameter list after the class's name::
         *
         *         class Mapping[KT, VT]:
         *             def __getitem__(self, key: KT) -> VT:
         *                 ...
         *             # Etc.
         *
         *     On older versions of Python, however, generic classes have to
         *     explicitly inherit from Generic.
         *
         *     After a class has been declared to be generic, it can then be used as
         *     follows::
         *
         *         def lookup_name[KT, VT](mapping: Mapping[KT, VT], key: KT, default: VT) -> VT:
         *             try:
         *                 return mapping[key]
         *             except KeyError:
         *                 return default */
        get: operations["List Electricity Tariff Standard Unit Rates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{product_code}/electricity-tariffs/{tariff_code}/standing-charges/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Abstract base class for generic types.
         *
         *     On Python 3.12 and newer, generic classes implicitly inherit from
         *     Generic when they declare a parameter list after the class's name::
         *
         *         class Mapping[KT, VT]:
         *             def __getitem__(self, key: KT) -> VT:
         *                 ...
         *             # Etc.
         *
         *     On older versions of Python, however, generic classes have to
         *     explicitly inherit from Generic.
         *
         *     After a class has been declared to be generic, it can then be used as
         *     follows::
         *
         *         def lookup_name[KT, VT](mapping: Mapping[KT, VT], key: KT, default: VT) -> VT:
         *             try:
         *                 return mapping[key]
         *             except KeyError:
         *                 return default */
        get: operations["List Electricity Tariff Standing Charges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{product_code}/gas-tariffs/{tariff_code}/standard-unit-rates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Abstract base class for generic types.
         *
         *     On Python 3.12 and newer, generic classes implicitly inherit from
         *     Generic when they declare a parameter list after the class's name::
         *
         *         class Mapping[KT, VT]:
         *             def __getitem__(self, key: KT) -> VT:
         *                 ...
         *             # Etc.
         *
         *     On older versions of Python, however, generic classes have to
         *     explicitly inherit from Generic.
         *
         *     After a class has been declared to be generic, it can then be used as
         *     follows::
         *
         *         def lookup_name[KT, VT](mapping: Mapping[KT, VT], key: KT, default: VT) -> VT:
         *             try:
         *                 return mapping[key]
         *             except KeyError:
         *                 return default */
        get: operations["List Gas Tariff Standard Unit Rates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/products/{product_code}/gas-tariffs/{tariff_code}/standing-charges/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Abstract base class for generic types.
         *
         *     On Python 3.12 and newer, generic classes implicitly inherit from
         *     Generic when they declare a parameter list after the class's name::
         *
         *         class Mapping[KT, VT]:
         *             def __getitem__(self, key: KT) -> VT:
         *                 ...
         *             # Etc.
         *
         *     On older versions of Python, however, generic classes have to
         *     explicitly inherit from Generic.
         *
         *     After a class has been declared to be generic, it can then be used as
         *     follows::
         *
         *         def lookup_name[KT, VT](mapping: Mapping[KT, VT], key: KT, default: VT) -> VT:
         *             try:
         *                 return mapping[key]
         *             except KeyError:
         *                 return default */
        get: operations["List Gas Tariff Standing Charges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quotes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description At least one electricity or gas meter-point must be included. A maximum of one electricity and one gas meter-point can be included at this time. For all meter-points, at least one of gsp or postcode must be included. All meter-points must be based in the UK, excluding Northern Ireland. All meter-points must belong to the same gsp or postcode. WARNING: This endpoint is only available to partner organisations. */
        post: operations["Create a quote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quotes/{code}/products/{product_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Use this endpoint after quote creation to send a quote summary email to the specified recipients if they wish to enact the quote at a later time. A quote share record is saved to the database for each recipient’s email address. WARNING: This endpoint is only available to partner organisations. */
        post: operations["Share a quote via email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/voice/twilio/enqueue-audio/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Twilio Enqueue Audio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Address: {
            address_line_1: string;
            address_line_2?: string;
            address_line_3?: string;
            town?: string;
            county?: string;
            postcode: string;
            delivery_point_identifier?: string;
        };
        /** @description This serializer is used to allow affiliates to pass a signup reward code when creating
         *     accounts which later will then give credit to the accounts once their payments start. */
        Affiliate: {
            /**
             * The code of an existing signup reward referral scheme that will be used for giving credit to the created account as a signup reward.
             * @default
             */
            signup_reward_code: string;
            /** The name of an existing organization that will be used to create an account for an affiliate. */
            organization_name?: string;
            affiliate_link_subdomain?: string;
        };
        Agreement: {
            /** MPRN or MPAN of the meter point getting a new agreement. */
            mpxn: string;
            /** Tariff code for the new agreements. */
            tariff_code: string;
            /**
             * Date (inclusive) the new agreement is valid from.
             * Format: date
             */
            valid_from_date: string;
            /**
             * Date (exclusive) the new agreement is valid to.
             * Format: date
             */
            valid_to_date?: string;
        };
        AgreementsCreated: {
            account_number: string;
            agreements: components["schemas"]["Agreement"][];
        };
        BespokeElectricityUnitRate: {
            /**
             * The rate type of the unit rate.
             * @description If the register_identifier is not provided, the rate type must be provided instead.
             *
             *     * `STANDARD` - Standard rate (pence per kWh)
             *     * `ECO7_DAY` - Day (or peak) rate (pence per kWh)
             *     * `ECO7_NIGHT` - Night (or off-peak) rate (pence per kWh)
             *     * `OFF_PEAK` - Additional off-peak rate for three-rate tariffs (pence per kWh)
             *     * `SUMMER_PEAK` - Summer peak rate (pence per kWh) for two-rate tariffs
             *     * `SUMMER_OFF_PEAK` - Summer off-peak rate (pence per kWh) for two-rate tariffs
             *     * `WINTER_PEAK` - Winter peak rate (pence per kWh) for two-rate tariffs
             *     * `WINTER_OFF_PEAK` - Winter off-peak rate (pence per kWh) for two-rate tariffs
             *     * `NUCLEAR_RAB` - Nuclear RAB rate (pence per day) for business tariffs
             *     * `TNUOS` - TNUoS rate (pence per day) for business tariffs
             *     * `CAPACITY_MARKET` - Capacity Market rate (pence per day) for business tariffs
             *     * `EV_DEVICE` - Electric vehicle device rate (pence per kWh) for sub-meter billing
             * @enum {string}
             */
            rate_type?: "STANDARD" | "ECO7_DAY" | "ECO7_NIGHT" | "OFF_PEAK" | "SUMMER_PEAK" | "SUMMER_OFF_PEAK" | "WINTER_PEAK" | "WINTER_OFF_PEAK" | "NUCLEAR_RAB" | "TNUOS" | "CAPACITY_MARKET" | "EV_DEVICE";
            /**
             * The value in pence per kWh of the charge (excluding VAT).
             * Format: decimal
             * @description This field should be used for gas meters.
             */
            unit_rate: string;
            /**
             * The value in pence per kWh of the charge (excluding VAT).
             * @description This field should be used for gas meters.
             *
             *     * `DD` - DD
             *     * `NDD` - NDD
             *     * `PP` - PP
             * @enum {string}
             */
            payment_method?: "DD" | "NDD" | "PP";
        };
        BespokePPSTariffRates: {
            /**
             * The value in pence per day of the charge (excluding VAT).
             * Format: decimal
             */
            standing_charge?: string;
            /**
             * The value in pence per kWh of the charge (excluding VAT).
             * Format: decimal
             * @description This field should be used for gas meters.
             */
            unit_rate?: string;
            /**
             * List of the value in pence per kWh of the charges (excluding VAT).
             * @description For elec meters, the unit rates are provided on a per register basis in this array.
             */
            unit_rates?: components["schemas"]["BespokeElectricityUnitRate"][];
            /**
             * The payment method for the rate.
             * @description * `DD` - Direct Debit
             *     * `NDD` - Non-Direct Debit
             *     * `PP` - Prepayment
             * @enum {string}
             */
            payment_method: "DD" | "NDD" | "PP";
        };
        BespokeTariffRates: {
            /**
             * The value in pence per day of the charge (excluding VAT).
             * Format: decimal
             */
            standing_charge?: string;
            /**
             * The value in pence per kWh of the charge (excluding VAT).
             * Format: decimal
             * @description This field should be used for gas meters.
             */
            unit_rate?: string;
            /**
             * List of the value in pence per kWh of the charges (excluding VAT).
             * @description For elec meters, the unit rates are provided on a per register basis in this array.
             */
            unit_rates?: components["schemas"]["BespokeElectricityUnitRate"][];
        };
        Business: {
            /** The name of the business. */
            name: string;
            /**
             * The registered number of the business.
             * @description This field is required for 'LIMITED' businesses.</p>
             */
            number?: string;
            /**
             * @description * `SOLE_TRADER` - SOLE_TRADER
             *     * `LIMITED` - LIMITED
             *     * `CHARITY` - CHARITY
             *     * `PARTNERSHIP` - PARTNERSHIP
             *     * `GOVERNMENT` - GOVERNMENT
             * @enum {string}
             */
            business_type: "SOLE_TRADER" | "LIMITED" | "CHARITY" | "PARTNERSHIP" | "GOVERNMENT";
            /** Whether the business is exempt from paying CCL (Climate Change Levy). */
            is_ccl_exempt: boolean;
            /** Whether the business is exempt from paying VAT. */
            is_vat_exempt: boolean;
            /** The head count of the business, i.e. number of staff. */
            head_count?: number;
            /**
             * The estimated annual turnover
             * @description In pounds £ (GBP)
             */
            annual_turnover?: number;
        };
        BusinessTariffRenewal: {
            /** List of all agreements to be created to the given account. */
            agreements: components["schemas"]["_Agreement"][];
        };
        Consumption: {
            readonly consumption: string;
            /** Format: date-time */
            interval_start: string;
            /** Format: date-time */
            interval_end: string;
        };
        /** @description Serializer to create an account via a REST API.
         *
         *     Temporary to allow for legacy behaviour where uplifts do not count towards quoted amounts,
         *     which is potentially only OEGB behaviour. */
        Create: {
            /**
             * A code to specify the account should be for a particular brand.
             * @description This is only required when creating an account in an instance with multiple brands and for which the requested brand is not the default brand of that instance.
             *
             *     * `OCTOPUS_ENERGY` - OCTOPUS_ENERGY
             *     * `COOP_ENERGY` - COOP_ENERGY
             *     * `LONDON_POWER` - LONDON_POWER
             * @default OCTOPUS_ENERGY
             * @enum {string}
             */
            brand_code: "OCTOPUS_ENERGY" | "COOP_ENERGY" | "LONDON_POWER";
            /**
             * A unique partner reference.
             * @description The reference provided should be unique per switch.
             */
            reference: string;
            /**
             * A datetime of when the account sale was made.
             * Format: date-time
             */
            sold_at?: string;
            /**
             * A preferred supply start date.
             * Format: date
             * @description Only include this field if the earliest possible supply startdate is not preferred.
             */
            preferred_ssd?: string;
            /**
             * @description * `BUSINESS` - BUSINESS
             *     * `DOMESTIC` - DOMESTIC
             *     * `BUSINESS OCCUPIER` - BUSINESS OCCUPIER
             *     * `OCCUPIER` - OCCUPIER
             *     * `MANAGED` - MANAGED
             *     * `PORTFOLIO LEAD` - PORTFOLIO LEAD
             *     * `SYSTEM` - SYSTEM
             *     * `BUSINESS VACANT` - BUSINESS VACANT
             *     * `DOMESTIC VACANT` - DOMESTIC VACANT
             *     * `ANONYMISED` - ANONYMISED
             * @enum {string}
             */
            account_type: "BUSINESS" | "DOMESTIC" | "BUSINESS OCCUPIER" | "OCCUPIER" | "MANAGED" | "PORTFOLIO LEAD" | "SYSTEM" | "BUSINESS VACANT" | "DOMESTIC VACANT" | "ANONYMISED";
            /**
             * @description * `CALL_CENTRE_INBOUND` - CALL_CENTRE_INBOUND
             *     * `CALL_CENTRE_OUTBOUND` - CALL_CENTRE_OUTBOUND
             *     * `INTERNET` - INTERNET
             *     * `FACE_TO_FACE` - FACE_TO_FACE
             * @enum {string}
             */
            source: "CALL_CENTRE_INBOUND" | "CALL_CENTRE_OUTBOUND" | "INTERNET" | "FACE_TO_FACE";
            /**
             * @description * `DIRECT` - Direct
             *     * `PRICE_COMPARISON` - Price comparison site
             *     * `TELESALES` - Telesales
             *     * `DIGI_TELESALES` - Digital telesales
             *     * `EVENTS` - Events
             *     * `FIELD_SALES` - Field sales
             *     * `AGGREGATOR` - Aggregator
             *     * `PARTNERSHIPS` - Partnerships
             *     * `NEW_TENANT` - New tenant
             *     * `MOVE_IN` - Move in
             *     * `WORKPLACE_POP_UP` - Workplace pop-up
             *     * `BROKER` - Broker
             *     * `PARENT_POWER` - Parent power
             *     * `PEOPLE_POWER` - People power
             *     * `GIFT_OF_KIT` - Gift of kit
             *     * `HIGH_REFERRER` - High referrer
             *     * `SUPPLIER_OF_LAST_RESORT` - Supplier of last resort
             *     * `ACQUISITION` - Acquisition
             *     * `WORKS_WITH_OCTOPUS` - Works with octopus
             *     * `LANDLORD` - Landlord
             *     * `DEBT_COLLECTION_AGENCY` - Debt collection agency
             *     * `OCTOPUS_TRUSTED_PARTNERS` - Octopus Trusted Partners
             * @enum {string}
             */
            sales_channel?: "DIRECT" | "PRICE_COMPARISON" | "TELESALES" | "DIGI_TELESALES" | "EVENTS" | "FIELD_SALES" | "AGGREGATOR" | "PARTNERSHIPS" | "NEW_TENANT" | "MOVE_IN" | "WORKPLACE_POP_UP" | "BROKER" | "PARENT_POWER" | "PEOPLE_POWER" | "GIFT_OF_KIT" | "HIGH_REFERRER" | "SUPPLIER_OF_LAST_RESORT" | "ACQUISITION" | "WORKS_WITH_OCTOPUS" | "LANDLORD" | "DEBT_COLLECTION_AGENCY" | "OCTOPUS_TRUSTED_PARTNERS";
            /** An optional segmentation of the sales channel, e.g. the names of the specific price comparison site, or the telesales organisation. */
            sales_subchannel?: string;
            billing_address: components["schemas"]["Address"];
            users: components["schemas"]["User"][];
            affiliate?: components["schemas"]["Affiliate"];
            /** An array of key value pairs for storing generic metadata relating to an account. */
            metadata?: components["schemas"]["Metadata"][];
            /** The referral code of an existing account linked to a Kraken referral scheme. */
            referral_code?: string;
            signup_reward_code?: string;
            /**
             * A unique reference to previous external account number or similar account identifier.
             * @description The account reference must be in NAMESPACE-VALUE format.
             */
            account_reference?: string;
            /** Whether this account is a change of tenancy at the property. */
            is_change_of_tenancy: boolean;
            /**
             * Communication delivery preference
             * @description When requires_postal_comms is True, then set to POSTAL, else set to EMAIL, when not provided it will be null.
             */
            requires_postal_comms?: boolean;
            /**
             * The read permission frequency the occupier grants to meter readings from smart meters.
             * @description * `MONTHLY` - Monthly
             *     * `DAILY` - Daily
             *     * `HALF_HOURLY` - Half-hourly
             * @enum {string}
             */
            smart_meter_read_permission?: "MONTHLY" | "DAILY" | "HALF_HOURLY";
            /**
             * The occupier’s interest in installing a smart meter.
             * @description * `SMETS2_INTEREST_PRIORITY` - Priority
             *     * `SMETS2_INTEREST_INTERESTED` - Interested
             *     * `SMETS2_INTEREST_NOT_AT_THE_MOMENT` - No interest at the moment, ask again later
             *     * `SMETS2_INTEREST_NOT_INTERESTED` - Not Interested
             * @enum {string}
             */
            smart_meter_interest?: "SMETS2_INTEREST_PRIORITY" | "SMETS2_INTEREST_INTERESTED" | "SMETS2_INTEREST_NOT_AT_THE_MOMENT" | "SMETS2_INTEREST_NOT_INTERESTED";
            /**
             * A code to indicate which type of smart tariff the customer is meant to onboard onto.
             * @description This is a restricted option. Please get in touch for information on whether this can be enabled and what the allowed options are.
             *
             *     * `AGILE` - Agile
             *     * `OCTOPUS_GO` - Octopus Go
             *     * `TESLA_IMPORT` - Tesla Import
             *     * `INTELLIGENT_OCTOPUS` - Intelligent Octopus
             *     * `GO_GREEN` - Go Green
             *     * `COSY_OCTOPUS` - Cosy Octopus
             *     * `OCTOPUS_FLUX` - Octopus Flux
             *     * `TRACKER` - Tracker
             *     * `AIRA_ZERO` - Aira Zero
             * @enum {string}
             */
            smart_onboarding_product_type?: "AGILE" | "OCTOPUS_GO" | "TESLA_IMPORT" | "INTELLIGENT_OCTOPUS" | "GO_GREEN" | "COSY_OCTOPUS" | "OCTOPUS_FLUX" | "TRACKER" | "AIRA_ZERO";
            business?: components["schemas"]["Business"];
            /** @description The payment details are required when using the method 'MONTHLY_DIRECT_DEBIT' but are optional if all the meters are of type PREPAYMENT'. The 'MONTHLY_DIRECT_PAYMENT' method is not available to all users. */
            payment?: components["schemas"]["Payment"];
            deposit?: components["schemas"]["Deposit"];
            /** @description At least one electricity or gas meter-point must be included. A maximum of two electricity and one gas meter-point can be included. All meter-points must be based in the Great Britain. All meter-points must belong to the same address. For an electricity meter-point, at least one of 'mpan' or 'address' must be included. At least one of 'consumption_standard' (standard tariff) or a combination of 'consumption_day' and 'consumption_night' (two-rate tariff) or 'consumption_day', 'consumption_night' and 'consumption_off_peak' (three-rate tariff) must be included depending on the type of tariff specified. */
            electricity_meter_points?: components["schemas"]["ElectricityMeterPoint"][];
            /** @description At least one electricity or gas meter-point must be included. A maximum of two electricity and one gas meter-point can be included. All meter-points must be based in the Great Britain. All meter-points must belong to the same address. For a gas meter-point, at least one of 'mprn' or 'address' must be included, as well as 'consumption_standard'. */
            gas_meter_points?: components["schemas"]["GasMeterPoint"][];
            /** @description The code of an existing legacy quote created using the legacy 'CreatQuote' mutation as part of the join supplier journey for this new customer. If the quote was generated as part of an affiliate session, the affiliate link and any query parameters belonging to the session will be associated with the created account. Note: only one of 'quote_code' and 'quote_request_code' should be provided in the input. */
            quote_code?: string;
            /** @description The code of an existing quote created using the 'QuoteNewMeterPoints' mutation as part of the join supplier journey for this new customer. If the quote was generated as part of an affiliate session, the affiliate link and any query parameters belonging to the session will be associated with the created account. Note: only one of 'quote_code' and 'quote_request_code' should be provided in the input. */
            quote_request_code?: string;
        };
        CreateQuoteError: {
            brand_code?: string[];
            electricity_meter_points?: string[];
            gas_meter_points?: string[];
            business_products_only?: string[];
            product_codes?: string[];
        };
        CreditScoreData: {
            score?: number;
            /**
             * @description * `LOW` - Low
             *     * `MID` - Medium
             *     * `HIGH` - High
             *     * `UNKNOWN` - Unknown
             * @enum {string}
             */
            risk_bracket?: "LOW" | "MID" | "HIGH" | "UNKNOWN";
        };
        Deposit: {
            amount?: number;
            key?: string;
            reason?: string;
        };
        Eco7ElectricityTariff: {
            code: string;
            /** Format: double */
            readonly standing_charge_exc_vat: number | null;
            /** Format: double */
            readonly standing_charge_inc_vat: number | null;
            /** Format: double */
            readonly online_discount_exc_vat: number;
            /** Format: double */
            readonly online_discount_inc_vat: number;
            /** Format: double */
            readonly dual_fuel_discount_exc_vat: number;
            /** Format: double */
            readonly dual_fuel_discount_inc_vat: number;
            readonly exit_fees_exc_vat: number;
            readonly exit_fees_inc_vat: number;
            readonly exit_fees_type: string;
            readonly links: components["schemas"]["Link"][];
            /** Format: double */
            readonly day_unit_rate_exc_vat: number | null;
            /** Format: double */
            readonly day_unit_rate_inc_vat: number | null;
            /** Format: double */
            readonly night_unit_rate_exc_vat: number | null;
            /** Format: double */
            readonly night_unit_rate_inc_vat: number | null;
        };
        ElectricityMeterPoint: {
            /**
             * The tariff code as stored by the supplier.
             * @description Must match an available tariff on the 'sold_at' datetime for the authenticating partner. Required if no 'quote_request_code' is supplied.
             */
            tariff_code?: string;
            /** @description The ID of the market supply quoted product returned by the 'QuoteNewMeterPoints' or 'QuoteNewMeterPointsOnBespokeProducts' mutation which was selected by the customer for this meter point. Required if a 'quote_request_code' is supplied. */
            quoted_product_id?: number;
            address?: components["schemas"]["Address"];
            current_supplier_name?: string;
            current_supplier_tariff?: string;
            /** Whether a smart meter is installed. The default is 'false'. */
            has_smart_meter?: boolean;
            /**
             * The expected annual consumption for the standard register in kWh.
             * @description Required if standard tariff.
             */
            consumption_standard?: number;
            /**
             * The amount to be added to the unit rate as commission (a string, pence per kWh).
             * Format: decimal
             */
            unit_rate_uplift?: string;
            /**
             * The amount to be added to the standing charge as commission (a string, pence per day).
             * Format: decimal
             */
            standing_charge_uplift?: string;
            fixed_tpi_fee?: number;
            quote: components["schemas"]["Quote"];
            /**
             * A json object containing bespoke tariff rates, if applicable.
             * @description Cannot be used in conjunction with 'bespoke_pps_tariff_rates'.
             */
            bespoke_tariff_rates?: components["schemas"]["BespokeTariffRates"];
            /** @description If applicable, must contain two objects: one for direct debit bespoke and another for non-direct debit bespoke rates. Cannot be used in conjunction with 'bespoke_tariff_rates'. */
            bespoke_pps_tariff_rates?: components["schemas"]["BespokePPSTariffRates"][];
            /**
             * @description The default is 'CREDIT', which represents any kind of traditional credit meter or smart meter. This field is mandatory for traditional prepay meters, for which the value 'PREPAYMENT' should be used.
             *
             *     * `CREDIT` - CREDIT
             *     * `PREPAYMENT` - PREPAYMENT
             * @default CREDIT
             * @enum {string}
             */
            meter_type: "CREDIT" | "PREPAYMENT";
            /** Format: date */
            preferred_ssd?: string;
            /** The meter-point identifier. */
            mpan?: string;
            /**
             * The expected annual consumption for the day/peak register in kWh.
             * @description Required if eco7 or three-rate tariff.
             */
            consumption_day?: number;
            /**
             * The expected annual consumption for the night/off-peak register in kWh.
             * @description Required if eco7 or three-rate tariff.
             */
            consumption_night?: number;
            /**
             * The expected annual consumption for the additional off-peak register in kWh.
             * @description Required if three-rate tariff.
             */
            consumption_off_peak?: number;
        };
        Emails: {
            /** An array of one or more email addresses to send the email to. */
            emails: string[];
        };
        ErrorResponse: {
            detail: string;
        };
        GasMeterPoint: {
            /**
             * The tariff code as stored by the supplier.
             * @description Must match an available tariff on the 'sold_at' datetime for the authenticating partner. Required if no 'quote_request_code' is supplied.
             */
            tariff_code?: string;
            /** @description The ID of the market supply quoted product returned by the 'QuoteNewMeterPoints' or 'QuoteNewMeterPointsOnBespokeProducts' mutation which was selected by the customer for this meter point. Required if a 'quote_request_code' is supplied. */
            quoted_product_id?: number;
            address?: components["schemas"]["Address"];
            current_supplier_name?: string;
            current_supplier_tariff?: string;
            /** Whether a smart meter is installed. The default is 'false'. */
            has_smart_meter?: boolean;
            /**
             * The expected annual consumption for the standard register in kWh.
             * @description Required if standard tariff.
             */
            consumption_standard: number;
            /**
             * The amount to be added to the unit rate as commission (a string, pence per kWh).
             * Format: decimal
             */
            unit_rate_uplift?: string;
            /**
             * The amount to be added to the standing charge as commission (a string, pence per day).
             * Format: decimal
             */
            standing_charge_uplift?: string;
            fixed_tpi_fee?: number;
            quote: components["schemas"]["Quote"];
            /**
             * A json object containing bespoke tariff rates, if applicable.
             * @description Cannot be used in conjunction with 'bespoke_pps_tariff_rates'.
             */
            bespoke_tariff_rates?: components["schemas"]["BespokeTariffRates"];
            /** @description If applicable, must contain two objects: one for direct debit bespoke and another for non-direct debit bespoke rates. Cannot be used in conjunction with 'bespoke_tariff_rates'. */
            bespoke_pps_tariff_rates?: components["schemas"]["BespokePPSTariffRates"][];
            /**
             * @description The default is 'CREDIT', which represents any kind of traditional credit meter or smart meter. This field is mandatory for traditional prepay meters, for which the value 'PREPAYMENT' should be used.
             *
             *     * `CREDIT` - CREDIT
             *     * `PREPAYMENT` - PREPAYMENT
             * @default CREDIT
             * @enum {string}
             */
            meter_type: "CREDIT" | "PREPAYMENT";
            /** Format: date */
            preferred_ssd?: string;
            /** The meter-point identifier. */
            mprn?: string;
        };
        GasTariff: {
            code: string;
            /** Format: double */
            readonly standing_charge_exc_vat: number | null;
            /** Format: double */
            readonly standing_charge_inc_vat: number | null;
            /** Format: double */
            readonly online_discount_exc_vat: number;
            /** Format: double */
            readonly online_discount_inc_vat: number;
            /** Format: double */
            readonly dual_fuel_discount_exc_vat: number;
            /** Format: double */
            readonly dual_fuel_discount_inc_vat: number;
            readonly exit_fees_exc_vat: number;
            readonly exit_fees_inc_vat: number;
            readonly exit_fees_type: string;
            readonly links: components["schemas"]["Link"][];
            /** Format: double */
            readonly standard_unit_rate_exc_vat: number | null;
            /** Format: double */
            readonly standard_unit_rate_inc_vat: number | null;
        };
        GridSupplyPoint: {
            group_id: string;
        };
        HistoricalCharge: {
            /** Format: double */
            readonly value_exc_vat: number;
            /** Format: double */
            readonly value_inc_vat: number;
            /** Format: date-time */
            readonly valid_from: string | null;
            /** Format: date-time */
            readonly valid_to: string | null;
            readonly payment_method: string | null;
        };
        Link: {
            href: string;
            method: string;
            rel: string;
        };
        Metadata: {
            /** Key on which the metadata will be stored. */
            key: string;
            /** A json object containing any arbitrary piece of data to store in relation to the account. */
            value: unknown;
        };
        PSR: {
            /** @description If true, indicates that the user should be signed up to the PSR but the categories are unknown. Therefore the user requires contacting to determine the categories. */
            requires_signup?: boolean;
        };
        PaginatedConsumptionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example https://api.octopus.energy/v1/electricity-meter-points/S1212345678901/meters/Z16N389556/consumption/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example https://api.octopus.energy/v1/electricity-meter-points/S1212345678901/meters/Z16N389556/consumption/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Consumption"][];
        };
        PaginatedGridSupplyPointList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example https://api.octopus.energy/v1/industry/grid-supply-points/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example https://api.octopus.energy/v1/industry/grid-supply-points/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["GridSupplyPoint"][];
        };
        PaginatedHistoricalChargeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example https://api.octopus.energy/v1/products/VAR-17-01-11/electricity-tariffs/E-1R-VAR-17-01-11-A/day-unit-rates/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example https://api.octopus.energy/v1/products/VAR-17-01-11/electricity-tariffs/E-1R-VAR-17-01-11-A/day-unit-rates/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["HistoricalCharge"][];
        };
        PaginatedProductsList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example https://api.octopus.energy/v1/products/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example https://api.octopus.energy/v1/products/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Products"][];
        };
        Payment: {
            /**
             * @description * `MONTHLY_DIRECT_DEBIT` - Monthly Direct Debit
             *     * `MONTHLY_DIRECT_PAYMENT` - POROB schedule, payment initiated by the customer
             *     * `BILL_TRIGGERED_DIRECT_DEBIT` - POROB Direct Debit Schedule
             * @enum {string}
             */
            method: "MONTHLY_DIRECT_DEBIT" | "MONTHLY_DIRECT_PAYMENT" | "BILL_TRIGGERED_DIRECT_DEBIT";
            /** The name associated with the bank account. */
            account_name?: string;
            /** The bank account number. */
            account_number?: string;
            /** The bank account sort code. */
            account_sort_code?: string;
            /**
             * The preferred day of the month for the payment request.
             * @description Only required for 'MONTHLY_DIRECT_DEBIT' schedules.
             */
            payment_day?: number;
            /** The number of days to delay the payment for a bill triggered schedule. */
            delay_days?: number;
        };
        Product: {
            code: string;
            full_name: string;
            /** @description This name will be shown to customers during sign-up */
            display_name: string;
            /** @description This will be shown to customers during sign-up */
            description: string;
            /** Is variable? */
            is_variable?: boolean;
            /** Is a green product? */
            is_green?: boolean;
            /** Is a tracker product? */
            is_tracker?: boolean;
            is_prepay?: boolean;
            /** Is a business product? */
            is_business?: boolean;
            readonly is_restricted: boolean;
            /** @description Duration of agreements using this product in months */
            term?: number | null;
            /** Format: date-time */
            available_from: string;
            /** Format: date-time */
            available_to?: string | null;
            /** Format: date-time */
            readonly tariffs_active_at: string;
            readonly single_register_electricity_tariffs: {
                [key: string]: {
                    [key: string]: components["schemas"]["StandardElectricityTariff"];
                };
            };
            readonly dual_register_electricity_tariffs: {
                [key: string]: {
                    [key: string]: components["schemas"]["Eco7ElectricityTariff"];
                };
            };
            readonly single_register_gas_tariffs: {
                [key: string]: {
                    [key: string]: components["schemas"]["GasTariff"];
                };
            };
            readonly sample_quotes: components["schemas"]["SampleQuotes"];
            readonly sample_consumption: components["schemas"]["SampleConsumption"];
            /** @description Historical charges can be browsed using the provided URLs. */
            readonly links: components["schemas"]["Link"][];
            readonly brand: string;
        };
        Products: {
            code: string;
            /**
             * @description * `IMPORT` - Import
             *     * `EXPORT` - Export
             * @enum {string}
             */
            direction?: "IMPORT" | "EXPORT";
            full_name: string;
            /** @description This name will be shown to customers during sign-up */
            display_name: string;
            /** @description This will be shown to customers during sign-up */
            description: string;
            /** Is variable? */
            is_variable?: boolean;
            /** Is a green product? */
            is_green?: boolean;
            /** Is a tracker product? */
            is_tracker?: boolean;
            is_prepay?: boolean;
            /** Is a business product? */
            is_business?: boolean;
            readonly is_restricted: boolean;
            /** @description Duration of agreements using this product in months */
            term?: number | null;
            /** Format: date-time */
            available_from: string;
            /** Format: date-time */
            available_to?: string | null;
            /** @description Historical charges can be browsed using the provided URLs. */
            readonly links: components["schemas"]["Link"][];
            readonly brand: string;
        };
        Quote: {
            /**
             * The estimated annual payment for this meter-point based on consumption.
             * @description This value must be provided in pence. For business quotes, the price is exclusive of VAT, while for non-business quotes, it should be inclusive of VAT.
             */
            annual_payment: number;
        };
        QuoteCreated: {
            code: string;
            gsp: string;
            readonly products: Record<string, never>[];
        };
        SampleConsumption: {
            /** Consumption type */
            electricity_single_rate: {
                [key: string]: number;
            };
            /** Consumption type */
            electricity_dual_rate: {
                [key: string]: number;
            };
            /** Consumption type */
            dual_fuel_single_rate: {
                [key: string]: number;
            };
            /** Consumption type */
            dual_fuel_dual_rate: {
                [key: string]: number;
            };
        };
        SampleQuotes: {
            /** Annual cost (inc or exc) */
            electricity_single_rate: {
                [key: string]: number;
            };
            /** Annual cost (inc or exc) */
            electricity_dual_rate: {
                [key: string]: number;
            };
            /** Annual cost (inc or exc) */
            dual_fuel_single_rate: {
                [key: string]: number;
            };
            /** Annual cost (inc or exc) */
            dual_fuel_dual_rate: {
                [key: string]: number;
            };
        };
        StandardElectricityTariff: {
            code: string;
            /** Format: double */
            readonly standing_charge_exc_vat: number | null;
            /** Format: double */
            readonly standing_charge_inc_vat: number | null;
            /** Format: double */
            readonly online_discount_exc_vat: number;
            /** Format: double */
            readonly online_discount_inc_vat: number;
            /** Format: double */
            readonly dual_fuel_discount_exc_vat: number;
            /** Format: double */
            readonly dual_fuel_discount_inc_vat: number;
            readonly exit_fees_exc_vat: number;
            readonly exit_fees_inc_vat: number;
            readonly exit_fees_type: string;
            readonly links: components["schemas"]["Link"][];
            /** Format: double */
            readonly standard_unit_rate_exc_vat: number | null;
            /** Format: double */
            readonly standard_unit_rate_inc_vat: number | null;
        };
        SuccessResponse: {
            /** Number of the newly created account */
            number: string;
        };
        User: {
            title?: string;
            given_name: string;
            family_name: string;
            /** Format: date */
            date_of_birth?: string;
            /**
             * Format: email
             * @description Cannot already be in use for an existing account.
             */
            email: string;
            mobile?: string;
            landline?: string;
            opted_in_for_marketing: boolean;
            /** @default false */
            opted_in_to_third_parties: boolean;
            /** Priority Services Register details for the user */
            psr?: components["schemas"]["PSR"];
            credit_score_data?: components["schemas"]["CreditScoreData"];
        };
        ValidationErrors: {
            emails: Record<string, never>;
        };
        ValidationOrDomainError: {
            errors: string[];
        };
        _Agreement: {
            /** MPRN or MPAN of the meter point getting a new agreement. */
            mpxn: string;
            /** Tariff code for the new agreements. */
            tariff_code: string;
            /**
             * Date (inclusive) the new agreement is valid from.
             * Format: date
             */
            valid_from_date: string;
            /**
             * Date (exclusive) the new agreement is valid to.
             * Format: date
             */
            valid_to_date?: string;
            /** Bespoke tariff rates for the new agreement, if applicable. */
            bespoke_tariff_rates?: components["schemas"]["_BespokeTariffRate"][];
            /** Commission applicable to this tariff renewal. */
            commission?: components["schemas"]["_Commission"];
        };
        _BespokeRegisterRate: {
            /**
             * The rate type of the unit rate.
             * @description If the register_identifier is not provided, the rate type must be provided instead.
             *
             *     * `STANDARD` - Standard rate (pence per kWh)
             *     * `ECO7_DAY` - Day (or peak) rate (pence per kWh)
             *     * `ECO7_NIGHT` - Night (or off-peak) rate (pence per kWh)
             *     * `OFF_PEAK` - Additional off-peak rate for three-rate tariffs (pence per kWh)
             *     * `SUMMER_PEAK` - Summer peak rate (pence per kWh) for two-rate tariffs
             *     * `SUMMER_OFF_PEAK` - Summer off-peak rate (pence per kWh) for two-rate tariffs
             *     * `WINTER_PEAK` - Winter peak rate (pence per kWh) for two-rate tariffs
             *     * `WINTER_OFF_PEAK` - Winter off-peak rate (pence per kWh) for two-rate tariffs
             *     * `NUCLEAR_RAB` - Nuclear RAB rate (pence per day) for business tariffs
             *     * `TNUOS` - TNUoS rate (pence per day) for business tariffs
             *     * `CAPACITY_MARKET` - Capacity Market rate (pence per day) for business tariffs
             *     * `EV_DEVICE` - Electric vehicle device rate (pence per kWh) for sub-meter billing
             * @enum {string}
             */
            rate_type?: "STANDARD" | "ECO7_DAY" | "ECO7_NIGHT" | "OFF_PEAK" | "SUMMER_PEAK" | "SUMMER_OFF_PEAK" | "WINTER_PEAK" | "WINTER_OFF_PEAK" | "NUCLEAR_RAB" | "TNUOS" | "CAPACITY_MARKET" | "EV_DEVICE";
            /**
             * The value in pence per kWh of the charge (excluding VAT).
             * Format: decimal
             * @description This field should be used for gas meters.
             */
            unit_rate: string;
            /**
             * The value in pence per kWh of the charge (excluding VAT).
             * @description This field should be used for gas meters.
             *
             *     * `DD` - DD
             *     * `NDD` - NDD
             *     * `PP` - PP
             * @enum {string}
             */
            payment_method?: "DD" | "NDD" | "PP";
            /** The identifier of the register to which this unit rate applies. */
            register_identifier?: string;
        };
        _BespokeTariffRate: {
            /**
             * The value in pence per day of the charge (excluding VAT).
             * Format: decimal
             */
            standing_charge: string;
            /**
             * The value in pence per kWh of the charge (excluding VAT).
             * Format: decimal
             * @description This field should be used for gas meters.
             */
            unit_rate?: string;
            /** Meter serial number to which the bespoke tariff applies */
            meter_serial_number: string;
            /** @description For elec meters, the unit rates are provided on a per register basis in this array. */
            registers?: components["schemas"]["_BespokeRegisterRate"][];
        };
        _Commission: {
            /**
             * Uplift in pence to be paid to the affiliate.
             * Format: decimal
             */
            unit_rate_uplift: string;
            /**
             * Uplift in pence to be paid to the affiliate.
             * Format: decimal
             */
            standing_charge_uplift?: string;
            fixed_tpi_fee?: number;
            /** Name of the affiliate organisation due the commission for this agreement. */
            affiliate_organisation_name: string;
            /** Sub-domain of the affiliate link due the commission for this agreement. */
            affiliate_link_subdomain?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "Create an account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create"];
            };
        };
        responses: {
            /** @description Account successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
            /** @description The submission has incurred an error, but requires further investigation from a member of our team in order to complete the request. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The submissions incurred validation errors that cannot be fixed by a member of our team. This may occur if the provided reference is a duplicate and the existing enrolment has not previously been rejected. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    "Renew a business tariff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Number of the account */
                account_number: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BusinessTariffRenewal"];
            };
        };
        responses: {
            /** @description Agreement(s) successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgreementsCreated"];
                };
            };
            /** @description Could not create agreement due to domain or validation errors. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationOrDomainError"];
                };
            };
            /** @description Incorrect authentication. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user does not have sufficient permissions for this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The account does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Intermittent internal error. If it persists, please get in touch with the support team. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Get Electricity Meter Point": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mpan: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ElectricityMeterPoint"];
                };
            };
        };
    };
    "List consumption for an electricity meter": {
        parameters: {
            query?: {
                /** @description Aggregates consumption over a specified time period. A day is considered to start and end at midnight in the server’s timezone. The default is that consumption is returned in half-hour periods. Accepted values are: * ‘hour’ * ‘day’ * ‘week’ * ‘month’ * ‘quarter’. */
                group_by?: string;
                /** @description Ordering of results returned. Default is that results are returned in reverse order from latest available figure. Valid values: * ‘period’, to give results ordered forward. * ‘-period’, (default), to give results ordered from most recent backwards. */
                order_by?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Page size of returned results. Default is 100, maximum is 25000 to give a full year of half-hourly consumption details. */
                page_size?: number;
                /** @description Show results from the given datetime (inclusive). This parameter can be provided on its own. */
                period_from?: string;
                /** @description Show results up to the given datetime (exclusive). You must also provide the period_from parameter in order to create a range. */
                period_to?: string;
            };
            header?: never;
            path: {
                mpan: string;
                serial_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedConsumptionList"];
                };
            };
        };
    };
    "List consumption for a gas meter": {
        parameters: {
            query?: {
                /** @description Aggregates consumption over a specified time period. A day is considered to start and end at midnight in the server’s timezone. The default is that consumption is returned in half-hour periods. Accepted values are: * ‘hour’ * ‘day’ * ‘week’ * ‘month’ * ‘quarter’. */
                group_by?: string;
                /** @description Ordering of results returned. Default is that results are returned in reverse order from latest available figure. Valid values: * ‘period’, to give results ordered forward. * ‘-period’, (default), to give results ordered from most recent backwards. */
                order_by?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Page size of returned results. Default is 100, maximum is 25000 to give a full year of half-hourly consumption details. */
                page_size?: number;
                /** @description Show results from the given datetime (inclusive). This parameter can be provided on its own. */
                period_from?: string;
                /** @description Show results up to the given datetime (exclusive). You must also provide the period_from parameter in order to create a range. */
                period_to?: string;
            };
            header?: never;
            path: {
                mprn: string;
                serial_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedConsumptionList"];
                };
            };
        };
    };
    "List Industry Grid Supply Points": {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A postcode to filter GSPs by. */
                postcode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGridSupplyPointList"];
                };
            };
        };
    };
    "Minimal Twilio Enqueue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "List Products": {
        parameters: {
            query?: {
                /** @description Show products available for new agreements on the given datetime. Defaults to current datetime, effectively showing products that are currently available. */
                available_at?: string;
                brand?: string;
                /** @description Show only business products */
                is_business?: boolean;
                /** @description Show only green products */
                is_green?: boolean;
                is_historical?: boolean;
                /** @description Show only pre-pay products */
                is_prepay?: boolean;
                /** @description Show only tracker products */
                is_tracker?: boolean;
                /** @description Show only variable products */
                is_variable?: boolean;
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProductsList"];
                };
            };
        };
    };
    "Retrieve a Product": {
        parameters: {
            query?: {
                /** @description The point in time in which to show the active charges. Defaults to current datetime. */
                tariffs_active_at?: string;
            };
            header?: never;
            path: {
                /** @description The code of the product to be retrieved, for example VAR-17-01-11. */
                product_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    "List Electricity Tariff Day Unit Rates": {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Page size of returned results. Default is 100, maximum is 1500 to give up to a month of half-hourly prices. */
                page_size?: number;
                /** @description Show results from the given datetime (inclusive). This parameter can be provided on its own. */
                period_from?: string;
                /** @description Show results up to the given datetime (exclusive). You must also provide the period_from parameter in order to create a range. */
                period_to?: string;
            };
            header?: never;
            path: {
                /** @description The code of the product to be retrieved, for example VAR-17-01-11. */
                product_code: string;
                /** @description The code of the tariff to be retrieved, for example E-1R-VAR-17-01-11-A. */
                tariff_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHistoricalChargeList"];
                };
            };
        };
    };
    "List Electricity Tariff Night Unit Rates": {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Page size of returned results. Default is 100, maximum is 1500 to give up to a month of half-hourly prices. */
                page_size?: number;
                /** @description Show results from the given datetime (inclusive). This parameter can be provided on its own. */
                period_from?: string;
                /** @description Show results up to the given datetime (exclusive). You must also provide the period_from parameter in order to create a range. */
                period_to?: string;
            };
            header?: never;
            path: {
                /** @description The code of the product to be retrieved, for example VAR-17-01-11. */
                product_code: string;
                /** @description The code of the tariff to be retrieved, for example E-1R-VAR-17-01-11-A. */
                tariff_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHistoricalChargeList"];
                };
            };
        };
    };
    "List Electricity Tariff Standard Unit Rates": {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Page size of returned results. Default is 100, maximum is 1500 to give up to a month of half-hourly prices. */
                page_size?: number;
                /** @description Show results from the given datetime (inclusive). This parameter can be provided on its own. */
                period_from?: string;
                /** @description Show results up to the given datetime (exclusive). You must also provide the period_from parameter in order to create a range. */
                period_to?: string;
            };
            header?: never;
            path: {
                /** @description The code of the product to be retrieved, for example VAR-17-01-11. */
                product_code: string;
                /** @description The code of the tariff to be retrieved, for example E-1R-VAR-17-01-11-A. */
                tariff_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHistoricalChargeList"];
                };
            };
        };
    };
    "List Electricity Tariff Standing Charges": {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Page size of returned results. Default is 100, maximum is 1500 to give up to a month of half-hourly prices. */
                page_size?: number;
                /** @description Show results from the given datetime (inclusive). This parameter can be provided on its own. */
                period_from?: string;
                /** @description Show results up to the given datetime (exclusive). You must also provide the period_from parameter in order to create a range. */
                period_to?: string;
            };
            header?: never;
            path: {
                /** @description The code of the product to be retrieved, for example VAR-17-01-11. */
                product_code: string;
                /** @description The code of the tariff to be retrieved, for example E-1R-VAR-17-01-11-A. */
                tariff_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHistoricalChargeList"];
                };
            };
        };
    };
    "List Gas Tariff Standard Unit Rates": {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Page size of returned results. Default is 100, maximum is 1500 to give up to a month of half-hourly prices. */
                page_size?: number;
                /** @description Show results from the given datetime (inclusive). This parameter can be provided on its own. */
                period_from?: string;
                /** @description Show results up to the given datetime (exclusive). You must also provide the period_from parameter in order to create a range. */
                period_to?: string;
            };
            header?: never;
            path: {
                /** @description The code of the product to be retrieved, for example VAR-17-01-11. */
                product_code: string;
                /** @description The code of the tariff to be retrieved, for example E-1R-VAR-17-01-11-A. */
                tariff_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHistoricalChargeList"];
                };
            };
        };
    };
    "List Gas Tariff Standing Charges": {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Page size of returned results. Default is 100, maximum is 1500 to give up to a month of half-hourly prices. */
                page_size?: number;
                /** @description Show results from the given datetime (inclusive). This parameter can be provided on its own. */
                period_from?: string;
                /** @description Show results up to the given datetime (exclusive). You must also provide the period_from parameter in order to create a range. */
                period_to?: string;
            };
            header?: never;
            path: {
                /** @description The code of the product to be retrieved, for example VAR-17-01-11. */
                product_code: string;
                /** @description The code of the tariff to be retrieved, for example E-1R-VAR-17-01-11-A. */
                tariff_code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedHistoricalChargeList"];
                };
            };
        };
    };
    "Create a quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Create"];
            };
        };
        responses: {
            /** @description The quote has been created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteCreated"];
                };
            };
            /** @description Validation errors. The error response payload will take the same field structure as the request payload. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateQuoteError"];
                };
            };
        };
    };
    "Share a quote via email": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
                product_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Emails"];
            };
        };
        responses: {
            /** @description No validation error and quote or quoted product found */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation errors per index of the email */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrors"];
                };
            };
            /** @description No quote / quoted product found for given quote_code / product_id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "Twilio Enqueue Audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
